[package]
name = "catsploit_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
rand = "0.8.5"
dyn-clone = "1.0.10"

[dev-dependencies]
ctor = "0.1.22"
env_logger = "0.9.0"
